theme = "dark_high_contrast"

[editor]
line-number = "relative"
mouse = false
auto-pairs = false 
completion-replace = true
color-modes = true
popup-border = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true

[editor.indent-guides]
render = true
character = "┊"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

# [editor.soft-wrap]
# enable = true
