[[language]]
name = "json"
language-servers = [ "vscode-json-language-server" ]
auto-format = true
formatter = { command = 'jq', args = ["--tab", "."] }
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "git-commit"
file-types = []

[language-server]
vscode-json-language-server = { command = "vscode-json-languageserver", args = ["--stdio"], config = { provideFormatter = true, json = { validate = { enable = true } } } }
qmlls = { command = "/opt/Qt/6.6.2/gcc_64/bin/qmlls" }
csharp-ls = { command = "csharp-ls" }
#omnisharp = { command = "OmniSharp", args = [ "--languageserver" ] , timeout=10000 }
